version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER:     spring
      POSTGRES_PASSWORD: spring
      POSTGRES_DB:       spring
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports: 
      - 9080:8080
    depends_on: 
      - db