package jp.mirageworld.spring.fileupload.entity;

import java.io.Serializable;

public class FilesKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column files.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table files
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column files.id
     *
     * @return the value of files.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column files.id
     *
     * @param id the value for files.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}