package jp.mirageworld.spring.fileupload.entity;

import java.io.Serializable;

public class FilesWithBLOBs extends FilesKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column files.file
     *
     * @mbg.generated
     */
    private byte[] file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table files
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column files.file
     *
     * @return the value of files.file
     *
     * @mbg.generated
     */
    public byte[] getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column files.file
     *
     * @param file the value for files.file
     *
     * @mbg.generated
     */
    public void setFile(byte[] file) {
        this.file = file;
    }
}